[window]
decorations = "None"
opacity = 0.7
startup_mode = "Maximized"

[font]
size = 15.0

[font.normal]
family = "IosevkaNerdFont"
style = "Regular"

[font.bold]
family = "IosevkaNerdFont"
style = "Bold"

[font.italic]
family = "IosevkaNerdFont"
style = "Italic"

[font.bold_italic]
family = "IosevkaNerdFont"
style = "Bold Italic"

#[font.normal]
#family = "JetBrainsMonoNerdFont"
#style = "Regular"
#
#[font.bold]
#family = "JetBrainsMonoNerdFont"
#style = "Bold"
#
#[font.italic]
#family = "JetBrainsMonoNerdFont"
#style = "Italic"
#
#[font.bold_italic]
#family = "JetBrainsMonoNerdFont"
#style = "Bold Italic"
